# Generated by Django 5.0 on 2024-03-20 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('surname', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(default=datetime.datetime.now)),
                ('photo', models.ImageField(upload_to='candidates/')),
                ('degree', models.CharField(choices=[('B.S.', 'Bachelors'), ('M.S.', 'Masters'), ('Ph.D.', 'Ph.D.')], max_length=20)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('role', models.IntegerField(choices=[(1, 'Admin'), (2, 'Candidate'), (3, 'Employee'), (4, 'Moderator')])),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('skill', models.ManyToManyField(related_name='candidates_with_skill', to='job.skill')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('education', models.ManyToManyField(related_name='candidates_attended', to='account.university')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
