# Generated by Django 5.0 on 2024-03-12 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('job', '0002_remove_vacancy_skills_vacancy_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='education',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='skill',
            field=models.ManyToManyField(related_name='candidates_with_skill', to='job.skill'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='education',
            field=models.ManyToManyField(related_name='candidates_attended', to='account.university'),
        ),
    ]
