# Generated by Django 5.0 on 2024-03-12 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_candidate_education_alter_candidate_skill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='photo',
            field=models.ImageField(upload_to='candidates/% Y/% m/% d/'),
        ),
    ]
