# Generated by Django 5.0 on 2024-03-12 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_remove_vacancy_skills_vacancy_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(upload_to='logo/% Y/% m/% d/'),
        ),
    ]
